### ISSUE TITLE
Staffs - too hard to find a staff

### ISSUE THREAD

**Issue by QuentinRa** [lgs-games/prim#7]
It's hard to buy staff, the list is too long. Maybe make things easier?

**Comment by QuentinRa** [comment]
Also it would be good if we can level up 1 10 20 50 100 and not just one by one.

**Comment by GeNarukami** [comment]
it would be even great if you add a maximum to level up depending on the amount of E and DD.

**Comment by QuentinRa** [comment]
Staffs won't be able to have the new requested features since we changed a lot about them. We may re-open this in the future.
